# Generated by Django 5.1.5 on 2025-03-05 12:37

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tags', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Work',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', ckeditor.fields.RichTextField()),
                ('image', models.ImageField(blank=True, upload_to='works/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('tags', models.ManyToManyField(related_name='Works', to='tags.tag')),
            ],
            options={
                'verbose_name': 'Work',
                'verbose_name_plural': 'Works',
                'ordering': ['-created_at'],
            },
        ),
    ]
